image:
  file: .gitpod.dockerfile

vscode:
  extensions:
    - streetsidesoftware.code-spell-checker
    - DavidAnson.vscode-markdownlint
    - Gruntfuggly.todo-tree
    - ms-vscode.hexeditor
    - tintinweb.vscode-decompiler
    - 13xforever.language-x86-64-assembly

workspaceLocation: '/workspace/ReverseEngineeringLinux'
